version: 0.2

env:
  variables:
    REGISTRY: "public.ecr.aws/risken"
    IMAGE_WEBSITE_BASE: "osint/website-base"
  parameter-store:
    GITHUB_USER: "/build/GITHUB_USER"
    GITHUB_TOKEN: "/build/GITHUB_TOKEN"

phases:
  install:
    commands:
      - echo "machine github.com" > ~/.netrc
      - echo "login ${GITHUB_USER}" >> ~/.netrc
      - echo "password ${GITHUB_TOKEN}" >> ~/.netrc
  pre_build:
    commands:
      - echo Setting environment variables
      - BUILD_OPT="--no-cache --pull"

      - echo Logging in to Amazon ECR...
      - codebuild-breakpoint
      - $(aws ecr get-login --no-include-email --region ${AWS_DEFAULT_REGION})
  build:
    commands:
      - echo Build subdomain base image started on `date`
      - TAG=${IMAGE_WEBSITE_BASE}_${OS}_${ARCH}
      - cd dockers/website-base
      - docker build ${BUILD_OPT} -t ${IMAGE_WPSCAN_BASE}:${TAG} .

      - echo Tagging the images...
      # tag the specific version
      - docker tag ${IMAGE_WEBSITE_BASE}:${TAG} ${REGISTORY}/${IMAGE_WEBSITE_BASE}:${TAG}

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...

      # specific version
      - docker push ${REGISTORY}/${IMAGE_WEBSITE_BASE}:${TAG}
