name: Pre Submit

on:
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  Tests:
    runs-on: ubuntu-latest
    env:
      GO_VERSION: 1.14
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set token for access internal repository
        run: git config --global url."https://${{ secrets.GO_MODULES_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Tests
        run: make go-test -j

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.sha }}
            ${{ runner.os }}-buildx-
            refs/head/master

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Osint Images
        uses: docker/build-push-action@v2
        with:
          context: src/osint
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GO_MODULES_TOKEN }}"
            "GITHUB_USER=${{ secrets.GO_MODULES_USER }}"

      - name: Build Subdomain Images
        uses: docker/build-push-action@v2
        with:
          context: src/subdomain
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GO_MODULES_TOKEN }}"
            "GITHUB_USER=${{ secrets.GO_MODULES_USER }}"

      - name: Build Website Images
        uses: docker/build-push-action@v2
        with:
          context: src/website
          platforms: linux/amd64
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
          secrets: |
            "GITHUB_TOKEN=${{ secrets.GO_MODULES_TOKEN }}"
            "GITHUB_USER=${{ secrets.GO_MODULES_USER }}"
